build(versioning): automate version metadata, add about dialog, enforce semantic versioning

diff --git a/.github/workflows/build-windows.yml b/.github/workflows/build-windows.yml
--- a/.github/workflows/build-windows.yml
+++ b/.github/workflows/build-windows.yml
@@ -63,10 +63,58 @@ jobs:
           echo "INKNOTE_VERSION=${GITHUB_REF_NAME#v}" >> $env:GITHUB_ENV
 
       # -------------------------
+      # Validate Semantic Version
+      # -------------------------
+      - name: Validate semantic version
+        if: startsWith(github.ref, 'refs/tags/')
+        run: |
+          if (-not "${{ github.ref_name }}" -match"^v\d+\.\d+\.\d+$) {
+            Write-Error "Invalid version tag. Use vMAJOR.MINOR.PATCH"
+            exit 1
+        }
+
+      # -------------------------
       - name: Set dev version
         if: "!startsWith(github.ref, 'refs/tags/')"
         run: |
           echo "INKNOTE_VERSION=dev-${{ github.sha }}" >> $env:GITHUB_ENV
+
+      # -------------------------
+      # Generate version file
+      # -------------------------
+      - name: Generate version file
+        run: |
+          @"
+          VSVersionInfo(
+            ffi=FixedFileInfo(
+              filevers=(${env:INKNOTE_VERSION//./,},0),
+              prodvers=(${env:INKNOTE_VERSION//./,},0),
+              mask=0x3f,
+              flags=0x0,
+              OS=0x40004,
+              fileType=0x1,
+              subtype=0x0,
+              date=(0,0)
+            ),
+            kids=[
+              StringFileInfo(
+                [
+                  StringTable(
+                    u'040904B0',
+                    [
+                      StringStruct(u'CompanyName', u'InkNote'),
+                      StringStruct(u'FileDescription', u'InkNote Text Editor'),
+                      StringStruct(u'FileVersion', u'${env:INKNOTE_VERSION}'),
+                      StringStruct(u'ProductName', u'InkNote'),
+                      StringStruct(u'ProductVersion', u'${env:INKNOTE_VERSION}')
+                    ]
+                  )
+                ]
+              ),
+              VarFileInfo([VarStruct(u'Translation', [1033, 1200])])
+            ]
+          )
+          "@ | Out-File -Encoding utf8 version.txt
 
       # -------------------------
       # Build executable
